version: "3"

services:
  nats:
    image: nats-streaming:0.22.0
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    entrypoint:
      - /nats-streaming-server
      - -cid
      - unichat
      - -p
      - "4222"
      - -m
      - "8222"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - 6379:6379

  # db:
  #   image: mongo
  #   container_name: db
  #   ports:
  #     - 27017:27017
