# @host = http://app.local
# @host = https://chat.cafe2hdaily.xyz
@host = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTYwNmZlYjBiNTg0ZWNmNGMzYWU0ZDUiLCJpYXQiOjE2MzM3MTAwNTl9.JwmrmybdYCrzHhIZI3EQmpmysj37ofYDUJmE8YQaxDM

###
POST {{host}}/signup
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}


###
POST {{host}}/signin
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
GET {{host}}/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTYwNmZlYjBiNTg0ZWNmNGMzYWU0ZDUiLCJpYXQiOjE2MzM3MTA1NjN9.hRHUKayJn2syGM4YoyscFrEaVTosbZzO3ehTmzKH5lE

###

GET {{host}}/api/messages

###
