# @host = http://app.local
@host = https://chat.cafe2hdaily.xyz
# @host = http://localhost:4000

###
POST {{host}}/api/signup
content-type: application/json

{
    "username": "user",
    "password": "user"
}


###
# @name signin
POST {{host}}/api/signin
content-type: application/json

{
    "username": "user",
    "password": "user"
}

###
GET {{host}}/api/user
Authorization: Bearer {{signin.response.body.token}}

###

GET {{host}}/api/messages

###
DELETE {{host}}/api/messages

###
