# @host = http://app.local
@host = https://chat.cafe2hdaily.xyz
# @host = http://localhost:4000
@chat_host = http://localhost:4001

###
POST {{host}}/api/users/signup
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}


###
# @name signin
POST {{host}}/api/users/signin
content-type: application/json

{
    "username": "user",
    "password": "user"
}

###
GET {{host}}/api/users/current
Authorization: Bearer {{signin.response.body.token}}

###
GET {{host}}/api/users/getList
Authorization: Bearer {{signin.response.body.token}}

###
DELETE {{host}}/api/users/{{signin.response.body.user._id}}
Authorization: Bearer {{signin.response.body.token}}

###
PUT {{host}}/api/users/{{signin.response.body.user._id}}
content-type: application/json
Authorization: Bearer {{signin.response.body.token}}

{
    "firstName": "user1"
}

###
# @name rooms
GET {{chat_host}}/api/chat/rooms

###
GET {{chat_host}}/api/chat/rooms/{{rooms.response.body[0]._id}}/messages

###
