apiVersion: skaffold/v2beta17
kind: Config
deploy:
  statusCheckDeadlineSeconds: 600
  kubectl:
    manifests:
      - ./k8s/local/deployments/*
      - ./k8s/local/pods/*
build:
  local:
    push: false
  artifacts:
    - image: unichat/chat
      context: chat
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
