apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: unichat-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: unichat@yopmail.com
    privateKeySecretRef:
      name: unichat-prod
    solvers:
      - http01:
          ingress:
            class: nginx
