apiVersion: v1
kind: Service
metadata:
  name: chat-mongo
  labels:
    app: chat-mongo
spec:
  ports:
    - name: chat-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: chat-mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chat-mongo
spec:
  selector:
    matchLabels:
      app: chat-mongo
  serviceName: "chat-mongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: chat-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: chat-mongo-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: chat-mongo-volume
      spec:
        storageClassName: mongodb
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
